##Problem 2
##Each new term in the Fibonacci sequence is generated by adding the previous
##two terms. By starting with 1 and 2, the first 10 terms will be:
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##By considering the terms in the Fibonacci sequence whose values do not
##exceed four million, find the sum of the even-valued terms.

## Notes:
## 

from timeit import default_timer as timer
from math import sqrt



# start timer
start = timer()

primes = set([2])
value = 3
number = 600851475143
factors = []
while value < sqrt(number):
    isPrime = True
    for k in primes:
        if value % k == 0:
            isPrime = False
            value += 2
    if isPrime:
        primes.add(value)
        if number % value == 0:
            #print(str(value))
            factors.append(value)
            number = int(number/value)
factors.append(number) # final number is also factor

print(max(factors))

end = timer()
print("Runtime: ",str(end-start)," s",sep="")
